pipeline{
    agent any
    stages{
        stage("Build"){
            steps{
                dir("walletCategory"){
                    sh "mvn clean compile"
                }
            }
        }
        stage("Test"){
            steps{
                dir("walletCategory"){
                    sh "mvn test"
                }
            }
        }
        stage("Dockerizing"){
            steps{
                dir("walletCategory"){
                    sh "mvn clean package -DskipTests"
                    sh "docker build -t walletcategory:${BUILD_NUMBER} ."
                }
            }
        }
    }
    post{
        always{
            sh "echo This will run always"
        }
        success{
            sh "echo This will only run if build is success"
        }
        failure{
            sh "echo This will only run if build fails"
        }
    }
}
